<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE group15 [
<!ELEMENT URN (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT coursetitle (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT student (URN,name,coursetitle)>
<!ELEMENT group15 (student+)>
<!ATTLIST group15 xml:lang CDATA #REQUIRED>
]>


<group15 xml:lang="en">
    <student>
        <URN>6426813</URN>
        <name>Callum Seymour</name>
        <coursetitle>CS</coursetitle>
        <email>cs00916@surrey.ac.uk</email>
    </student>
    <student>
        <URN>6407279</URN>
        <name>Sam Rowe</name>
        <coursetitle>CIT</coursetitle>
        <email>sr00584@surrey.ac.uk</email>
    </student>
    <student>
        <URN>6416585</URN>
        <name>Robert Bacon</name>
        <coursetitle>CS</coursetitle>
        <email>rb00573@surrey.ac.uk</email>
    </student>
    <student>
        <URN>6460017</URN>
        <name>Thushanthy Thillainathan</name>
        <coursetitle>CIT</coursetitle>
        <email>tt00308@surrey.ac.uk</email>
    </student>
    <student>
        <URN>6437280</URN>
        <name>Robbie Murray</name>
        <coursetitle>CS</coursetitle>
        <email>rm00727@surrey.ac.uk</email>
    </student>
    <student>
        <URN>6429748</URN>
        <name>Lukas Rygh</name>
        <coursetitle>CS</coursetitle>
        <email>lr00341@surrey.ac.uk</email>
    </student>
</group15>