<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE info[
<!ELEMENT info (name,age,birthday,family,places_lived)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT birthday (#PCDATA)>
<!ELEMENT family (person)>
<!ELEMENT person (person_name,relation)>
<!ELEMENT person_name (#PCDATA)>
<!ELEMENT relation (#PCDATA)>
<!ELEMENT places_lived (place)>
<!ELEMENT place (location,time_lived)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT time_lived (#PCDATA)>
]>
<info>
	<name>Callum Seymour</name>
	<age>18</age>
	<birthday>18-07-1998</birthday>
	<family>
		<person>
			<person_name>Petra Seymour</person_name>
			<relation>Mother</relation>
		</person>
		<person>
			<person_name>Neil Seymour</person_name>
			<relation>Father</relation>
		</person>
		<person>
			<person_name>Kieran Seymour</person_name>
			<relation>Brother</relation>
		</person>
		<person>
			<person_name>Rosie</person_name>
			<relation>Dog</relation>	
		</person>
		<person>
			<person_name>Tony Delgado</person_name>
			<relation>Grandad</relation>
		</person>
		<person>
			<person_name>David Seymour</person_name>
			<relation>Grandad</relation>
		</person>
		<person>
			<person_name>Elaine Bools</person_name>
			<relation>Grandmother</relation>
		</person>
		<person>
			<person_name>Maggie Desa</person_name>
			<relation>Grandmother</relation>	
		</person>
	</family>
	<places_lived>
		<place>
			<location>Lambeth</location>
			<time_lived>3 years</time_lived>
		</place>
		<place>
			<location>Croydon</location>
			<time_lived>1 year</time_lived>
		</place>
		<place>	
			<location>Battersea</location>
			<time_lived>12 years</time_lived>
		</place>
		<place>	
			<location>Kent</location>
			<time_lived>2 years</time_lived>
		</place>
		<place>			
			<location>Guildford</location>
			<time_lived>Current residence (lived for 2 months)</time_lived>
		</place>
	</places_lived>
</info>