<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pcspecs [
    <!ELEMENT component (name|type)*>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT pcspecs (component)*>
    <!ATTLIST pcspecs xml:lang CDATA #REQUIRED>
]>

<pcspecs xml:lang="en">
    <component>
        <name>i5 2500k @ 4.4GHz</name>
        <type>Processor</type>
    </component>
    <component>
        <name>EVGA GTX 980</name>
        <type>Graphics Card</type>      
    </component>
    <component>
        <name>16GB Corsair Vengeance</name>
        <type>RAM</type>         
    </component>
    <component>
        <name>512GB SSD</name>
        <type>Storage</type>         
    </component>
    <component>
        <name>2TB HDD</name>
        <type>Storage</type>         
    </component>    
</pcspecs>